= VViki

image::vviki.svg[VViki Logo,align=center]

== Overview

VViki is a tiny AsciiDoc-flavored wiki plugin for Vim.
It was inspired by link:https://github.com/vimwiki/vimwiki[VimWiki], 
uses Vim's existing AsciiDoc syntax highlighting,
and aims to be extremely lightweight.

== Features / Usage

* Hit Enter on a word to create a link
* Hit Enter on a link to edit that page (or open URL in a browser)
* Backspace opens previous page


== Install

=== Vundle

Add this to your plugin list (in your `.vimrc` file):

----
Plugin 'ratfactor/vviki'
----

Then run `:source %` and `:BundleInstall`.

== Setup

Add something like this to your `.vimrc`:

----
" VViki setup
let g:vviki_root = "~/wiki"
let g:vviki_ext  = ".adoc"
nnoremap <leader>ww :e ~/wiki/index.adoc<cr>
----

This will set the root of your wiki to `~/wiki`.
Any file with a `.adoc` extension in that directory (or subdirectory) will have wiki functionality.

It also maps the `<leader>ww` key sequence to open the index (start page) of your wiki, just like VimWiki. (To see your leader key, try `:echo mapleader`.)

Note: VViki does not create directories, so you'll need to create `~/wiki` if it does not already exist.


== Why?

I love link:https://github.com/vimwiki/vimwiki[VimWiki].
I also love AsciiDoc, but VimWiki doesn't support AsciiDoc syntax.
I put a day or two into adding full AsciiDoc support to VimWiki, but eventually concluded, "it would be faster just to create my own plugin."  And it was!

VViki aims to "do one thing and do it well".
This table explains the difference:

[options="header"]
|===
|Feature|VimWiki|VViki
|Wiki functionality|X|X
|Syntax highlighting|X|
|Tooling (search, HTML export, etc.)|X|
|===


== TODO

* [x] Absolute vs relative internal links
* [x] Make VViki a "real" plugin
* [x] Fix bug with description in link macros - need proper line parsing
* [x] Try using 'conceal' for syntax to display pretty links
* [x] Configurable wiki path
* [x] Configurable wiki file extension
* [x] Add default "index" files for "directory/" wiki paths
* [x] Start help doc
* [x] Finish help doc
* [x] Global setting to turn off link syntax conceal
* [ ] Add <tab> key link navigation (jump to next link)
* [ ] Consider creating directories as needed (limit to wiki root)
* [ ] Release 1.0
* [ ] Wishlist: some sort of shortcut (with pattern matching) to add
      links to existing wiki pages
* [ ] Wishlist: checklist shortcuts (check/uncheck [ ] boxes)


== License

MIT License

Copyright (c) 2020 Dave Gauer

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
