== Vwlite

The name comes from "VimWiki Lite". It's a tiny re-implementation of the core features of VimWiki I love and use daily.

But please call it "Vwlite" (maybe pronounced "vowelite?") and not "VimWiki Lite" because I don't want people to think this is associated with VimWiki (which is its own awesome, well-maintained project).

=== Features

* Hit Enter on a word to create a link
* Hit Enter on a link to edit that page (or open URL)
* Backspace opens previous page

=== Why?

I wanted VimWiki to support AsciiDoc syntax, but found that syntax was deeply tied to VimWiki functionality.
Full support for AsciiDoc was going to mean hacking lots of VimWiki features I don't actually use myself.

Plus, I was already using my own scripts to create diary entries, etc. So I wasn't benefitting much from the bulk.

The big idea here is to "do one thing and do it well". Keep these things separate:

1. Wiki functionality (me!)
2. Syntax highlighting (built-in Vim or plugin)
3. Searching, filtering (Silver Searcher, ripgrep, etc., FZF)
4. Exporting to HTML (AsciiDoctor, etc.)

So I've written my own plugin that is as small as possible, while supporting the same core wiki functionality from VimWiki that I love so much.

=== Quick Dev

F4 opens a test wiki and the plugin and sources it.

Thereafter, F5 sources the plugin again and swaps back and forth between the wiki and plugin in splits.  Love it.

----
"
" In ~/.vimrc
"
let g:vwlite_root = "~/vwlite"
let g:vwlite_ext  = ".adoc"
" Quick development: hit F5 to save, source, and jump to split window
function! Devthis()
	let l:pluginsrc = '~/d/proj/vwlite/vwlite.vim'
	exe "nnoremap <F5> :w\<cr>:so ".l:pluginsrc."\<cr>\<C-w>\<C-w>"
	exe "so ".l:pluginsrc
	exe "edit ".l:pluginsrc
	exe "split ".g:vwlite_root."/index.adoc"
endfunction

" Setup dev environment for vw lite plugin
nnoremap <F4> :call Devthis()<cr>
----
